name: Build & Push Containers

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  prepare:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
