name: Build & Push Containers

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Success
        run: echo 'Success!'
