name: Build & Push Containers

on:
  workflow_run:
    workflows: [Run Tests]
    types:
      - completed

jobs:
  prepare:
    name: "Prepare 🚧"
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

  build:
    name: "continue"
    needs: [prepare]
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo 'hi'
