name: Build & Push Containers

on:
  push:
    branches: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.sha }}
          wait-interval: 10
          running-workflow-name: run-tests
          check-name: run-tests

      - name: Success
        run: echo 'Success!'
